services:
  postgres:
    image: postgres
    container_name: postgresmicroservice
    environment:
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postresql/data
volumes:
  pgdata: